/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Aplicacion.ServicioUsuario;

/**
 *
 * @author CCNAR
 */
public class ModuloUsuario extends javax.swing.JFrame {

    /**
     * Creates new form agregarUsuario
     */
    public ModuloUsuario() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.btn_eliminar_user.setVisible(false);
        this.btn_modificar_user.setVisible(false);
        this.btn_nuevo_user.setVisible(false);
        this.setTitle("Usuarios");
        ServicioUsuario servUser = new ServicioUsuario(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_usuario = new javax.swing.JTable();
        btn_crear_user = new javax.swing.JButton();
        btn_modificar_user = new javax.swing.JButton();
        btn_eliminar_user = new javax.swing.JButton();
        btn_nuevo_user = new javax.swing.JButton();
        btn_atras = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Constantia", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apellido:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, 30));

        jLabel2.setFont(new java.awt.Font("Constantia", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Usuarios");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 290, -1));

        jLabel3.setFont(new java.awt.Font("Constantia", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 120, 30));

        txt_apellido.setFont(new java.awt.Font("Constantia", 2, 12)); // NOI18N
        jPanel1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 170, 30));

        txt_nombre.setFont(new java.awt.Font("Constantia", 2, 12)); // NOI18N
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 170, 30));

        tb_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido"
            }
        ));
        jScrollPane2.setViewportView(tb_usuario);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 430, 240));

        btn_crear_user.setBackground(new java.awt.Color(51, 51, 51));
        btn_crear_user.setFont(new java.awt.Font("Constantia", 2, 12)); // NOI18N
        btn_crear_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_crear_user.setText("Crear");
        jPanel1.add(btn_crear_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 100, -1));

        btn_modificar_user.setBackground(new java.awt.Color(51, 51, 51));
        btn_modificar_user.setFont(new java.awt.Font("Constantia", 2, 12)); // NOI18N
        btn_modificar_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar_user.setText("Modificar");
        jPanel1.add(btn_modificar_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 100, -1));

        btn_eliminar_user.setBackground(new java.awt.Color(51, 51, 51));
        btn_eliminar_user.setFont(new java.awt.Font("Constantia", 2, 12)); // NOI18N
        btn_eliminar_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar_user.setText("Eliminar");
        jPanel1.add(btn_eliminar_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 100, -1));

        btn_nuevo_user.setBackground(new java.awt.Color(51, 51, 51));
        btn_nuevo_user.setFont(new java.awt.Font("Constantia", 2, 12)); // NOI18N
        btn_nuevo_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevo_user.setText("Nuevo");
        jPanel1.add(btn_nuevo_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 100, -1));

        btn_atras.setBackground(new java.awt.Color(51, 51, 51));
        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/izquierda.png"))); // NOI18N
        jPanel1.add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_atras;
    public javax.swing.JButton btn_crear_user;
    public javax.swing.JButton btn_eliminar_user;
    public javax.swing.JButton btn_modificar_user;
    public javax.swing.JButton btn_nuevo_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable tb_usuario;
    public javax.swing.JTextField txt_apellido;
    public javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
