/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Aplicacion.ServicioVinculacion;

/**
 *
 * @author CCNAR
 */
public class ModuloVinculacion extends javax.swing.JFrame {

    /**
     * Creates new form ModuloVinculacion
     */
    public ModuloVinculacion() {
        initComponents();
        this.setTitle("Vinculación");
        this.setLocationRelativeTo(this);
        ServicioVinculacion serv = new ServicioVinculacion(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_telefono_user = new javax.swing.JTable();
        btn_crear_tel = new javax.swing.JButton();
        btn_modificar_tel = new javax.swing.JButton();
        btn_atras = new javax.swing.JButton();
        txt_cant = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_usuario_vin = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Constantia", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Números Teléfonicos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 290, -1));

        jLabel3.setFont(new java.awt.Font("Constantia", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Teléfono:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 30));

        txt_telefono.setFont(new java.awt.Font("Constantia", 2, 18)); // NOI18N
        jPanel1.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 160, 30));

        tb_telefono_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Teléfono", "Vinculado"
            }
        ));
        jScrollPane2.setViewportView(tb_telefono_user);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 310, 270));

        btn_crear_tel.setBackground(new java.awt.Color(51, 51, 51));
        btn_crear_tel.setFont(new java.awt.Font("Constantia", 2, 12)); // NOI18N
        btn_crear_tel.setForeground(new java.awt.Color(255, 255, 255));
        btn_crear_tel.setText("Vincular");
        jPanel1.add(btn_crear_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 100, -1));

        btn_modificar_tel.setBackground(new java.awt.Color(51, 51, 51));
        btn_modificar_tel.setFont(new java.awt.Font("Constantia", 2, 12)); // NOI18N
        btn_modificar_tel.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar_tel.setText("Desvincular");
        jPanel1.add(btn_modificar_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 100, -1));

        btn_atras.setBackground(new java.awt.Color(51, 51, 51));
        btn_atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/izquierda.png"))); // NOI18N
        jPanel1.add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        txt_cant.setEditable(false);
        txt_cant.setFont(new java.awt.Font("Constantia", 2, 18)); // NOI18N
        jPanel1.add(txt_cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 30, 30));

        tb_usuario_vin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido"
            }
        ));
        jScrollPane3.setViewportView(tb_usuario_vin);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 320, 270));

        jLabel4.setFont(new java.awt.Font("Constantia", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 120, 30));

        txt_nombre.setFont(new java.awt.Font("Constantia", 2, 18)); // NOI18N
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 170, 30));

        jLabel5.setFont(new java.awt.Font("Constantia", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Usuarios");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 290, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloVinculacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloVinculacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloVinculacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloVinculacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloVinculacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_atras;
    public javax.swing.JButton btn_crear_tel;
    public javax.swing.JButton btn_modificar_tel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable tb_telefono_user;
    public javax.swing.JTable tb_usuario_vin;
    public javax.swing.JTextField txt_cant;
    public javax.swing.JTextField txt_nombre;
    public javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
